version: '3.8'

x-aws-config: 
  &aws-env
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}

x-ms-config:
  &ms-env
  LOKI_ENDPOINT: http://loki:3100/loki/api/v1/push
  LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
  GATEWAY_IP: ${GATEWAY_IP}


services:
  ms-authenticate:
    build: ms-authenticate
    environment:
      <<: [*aws-env, *ms-env]
      PORT: 5000
      MONGO_URL: mongodb://ms-user-db:27017/ms_user_db
      JWT_SECRET: ${JWT_SECRET}
      JWT_KONG_KEY: ${JWT_KONG_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      APP_NAME: ms-authenticate
    depends_on:
      - ms-user-db
    networks:
      - ms-net
      
  ms-user:
    build: ms-user
    environment:
      <<: [*aws-env, *ms-env]
      PORT: 5002
      MONGO_URL: mongodb://ms-user-db:27017/ms_user_db
      APP_NAME: ms-user

    depends_on:
      - ms-user-db
    networks:
      - ms-net

  ms-review:
    build: ms-review
    environment:
      <<: [*aws-env, *ms-env]
      PORT: 5001
      MONGO_URL: mongodb://ms-review-db:27017/ms_review_db
      APP_NAME: ms-review

    depends_on:
      - ms-review-db
    networks:
      - ms-net

  ms-user-db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=ms_user_db
    networks:
      - ms-net

  ms-review-db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=ms_review_db
    networks:
      - ms-net
      
  ms-frontend:
    build: 
      context: ms-frontend
    environment: # Only variables prefixed with VITE_ are exposed to the client.
      - VITE_GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - VITE_GOOGLE_API_MAP_ID=${GOOGLE_API_MAP_ID}
    networks:
      - ms-net

networks:
  ms-net:
    name: ms-net