version: '3.9'

x-pg-config: &pg-env
  POSTGRES_DB: kong
  POSTGRES_USER: kong
  POSTGRES_PASSWORD: password

x-kong-config: &kong-env
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: kong
  KONG_PG_HOST: kong-database
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: password


services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    networks:
      - ms-net
    ports:
      - "5432:5432"
    environment:
      <<: *pg-env

  kong-migrations:
    image: kong/kong-gateway:3.6.1.0
    container_name: kong-migrations
    command: kong migrations bootstrap 
    networks:
      - ms-net
    environment:
      <<: *kong-env
    depends_on:
      - kong-database
    
  kong-migrations-up:
    image: kong/kong-gateway:3.6.1.0
    container_name: kong-migrations-up
    command: kong migrations up && kong migrations finish 
    networks:
      - ms-net
    environment:
      <<: *kong-env
    depends_on:
      - kong-database

  kong-gateway:
    image: kong/kong-gateway:3.6.1.0
    container_name: kong-gateway
    networks:
      - ms-net
    ports:
      - "8000:8000"
      # - "8443:8443"
      - "8001:8001"
      # - "8444:8444"
      - "8002:8002"
      # - "8445:8445"
      # - "8003:8003"
      # - "8004:8004"
    environment:
      <<: *kong-env
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:${KONG_ADMIN_PORT:-8001}
      KONG_PROXY_LISTEN: 0.0.0.0:${KONG_PROXY_PORT:-8000}
    depends_on:
      - kong-database
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    

networks:
  ms-net: