version: '3.8'

x-aws-config: 
  &aws-env
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: us-east-1
  S3_ENDPOINT_URL: http://localstack:4566

services:

  # 
  # Microservices
  # 

  ms-authenticate:
    build: ms-authenticate
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://ms-user-db:27017/ms_user_db
    ports:
      - "9000:5000" # Expose port 8000 on the host, maps to port 5000 inside the container
    volumes:
      - ./ms-authenticate/app:/code/app # Map the host app directory to the container - direct reloads TODO create a seperate dev compose? when setup done
    depends_on:
      - ms-user-db
    networks:
      - ms-net
      
  ms-user:
    build: ms-user
    environment:
      <<: *aws-env
      PORT: 5002
      MONGO_URL: mongodb://ms-user-db:27017/ms_user_db
    ports:
      - "9002:5002" # Expose port 8000 on the host, maps to port 5000 inside the container
    volumes:
      - ./ms-user/app:/code/app # Map the host app directory to the container - direct reloads TODO create a seperate dev compose? when setup done
    depends_on:
      - ms-user-db
    networks:
      - ms-net

  ms-review:
    build: ms-review
    environment:
      - PORT=5001
      - MONGO_URL=mongodb://ms-review-db:27017/ms_review_db
    ports:
      - "9001:5001"
    volumes:
      - ./ms-review/app:/code/app
    depends_on:
      - ms-review-db
    networks:
      - ms-net

  ms-user-db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=ms_user_db
    ports:
      - "10000:27017"
    volumes:
      - ms-user-db-volume:/data/db
    networks:
      - ms-net

  ms-review-db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=ms_review_db
    ports:
      - "10001:27017"
    volumes:
      - ms-review-db-volume:/data/db
    networks:
      - ms-net
      
  ms-frontend:
    build: 
      context: ms-frontend
      dockerfile: LocalDockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./ms-frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - ms-net

  localstack:
    container_name: "localstack-main"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./support/localstack/localstack-setup.sh:/etc/localstack/init/ready.d/script.sh"
    networks:
      - ms-net

  #
  # KONG
  #

volumes:
  ms-user-db-volume:
  ms-review-db-volume:

networks:
  ms-net: