_format_version: "3.0"


_transform: true


_comment: This is a top level comment, and must be a string

services:
- name: post-service
  url: http://ms-post:5001
  routes:
  - name: post-route
    paths:
    - /posts

- name: authenticate-service
  url: http://ms-authenticate:5000
  routes:
  - name: authenticate-route
    paths:
    - /authenticator

- name: user-service
  url: http://ms-user:5002
  tags:
  routes:
  - name: user-route
    paths:
    - /users

- name: frontend-service
  url: http://ms-frontend:8080
  tags:
  routes:
  - name: frontend-route
    paths:
    - /

plugins:
- name: jwt
  service: post-service
  enabled: true
  config:
    key_claim_name: kid
    claims_to_verify:
    - exp

consumers:
- username: login_server_issuer
  jwt_secrets:
    - key: "ooNKWeo0vijweijrKn234123J93c0qkD"
      secret: "H8WBDhQlcfjoFmIiYymmkRm1y0A2c5WU"