apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: ddjskne441wqoe
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000
    editable: true
    isDefault: true