apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-review
  name: ms-review
spec:
  ports:
  - port: 8080
    name: tcp
    protocol: TCP
    targetPort: 8080
  selector:
    app: ms-review
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-review
  name: ms-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-review
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-review
    spec:
      containers:
      - image: b193/ms-review:latest
        name: ms-review
        ports:
        - containerPort: 8080
        # env:
        #   - name: NODE_NAME
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: spec.nodeName
        #   - name: POD_NAME
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: metadata.name
        #   - name: POD_NAMESPACE
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: metadata.namespace
        #   - name: POD_IP
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: status.podIP
        # resources: {}
