name: Build, Test, and Upload Coverage to Codecov

on: [push, pull_request]

jobs:
  test_and_upload_coverage:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 2375:2375
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

   - name: Install Codecov CLI
        run: |
          python -m pip install --upgrade pip
          pip install codecov
  
    - name: Run Tests and Upload Coverage for Modified Services
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        bash ./.github/uploadCodeReport.sh '*'