name: Build and Push Docker images

on:
  push:
    tags:
       - '*'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  TARGET_BRANCH: 'main' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: fetch all history for all branches and tags

      - name: Check if tag is on target branch
        id: check-branch
        run: |
          BRANCH_EXISTS=$(git branch --all --contains ${{ github.ref }} | grep 'remotes/origin/${{ env.TARGET_BRANCH }}')
          echo "IS_TARGET_BRANCH=$(if [ -z "$BRANCH_EXISTS" ]; then echo 'false'; else echo 'true'; fi)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        if: env.IS_TARGET_BRANCH == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: env.IS_TARGET_BRANCH == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Determine the version
        if: env.IS_TARGET_BRANCH == 'true'
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Read services from config
        if: env.IS_TARGET_BRANCH == 'true'
        run: |
          SERVICES=$(cat support/services.conf | tr '\r\n' ' ')
          echo "SERVICES=$SERVICES" >> $GITHUB_ENV
          echo $SERVICES

      - name: Build and push Docker images
        if: env.IS_TARGET_BRANCH == 'true'
        run: |
          for SERVICE in $SERVICES; do
            echo "Building and pushing Docker image for $SERVICE"
            VERSIONED_IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/ase-social-network_$SERVICE:${{ env.VERSION }}"
            LATEST_IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/ase-social-network_$SERVICE:latest"
            
            docker buildx build "$SERVICE" -f "$SERVICE/Dockerfile.build" --push --tag "$VERSIONED_IMAGE_NAME" --tag "$LATEST_IMAGE_NAME"
          done
