name: Build and Push Docker images

on:
  push:
    branches:
      - feature-CIintegration-separate-enviroments  # Trigger on pushes to the main branch, adjust if necessary
    # tags:
    #   - 'v*'  # This will trigger the workflow on tags like v1.0, v2.0, etc.

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine the version
      id: get_version
      run: echo "VERSION=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
    
    - name: Read service folders from config
      id: read_folders
      run: |
        echo "FOLDERS=$(cat /support/services.conf | xargs)" >> $GITHUB_ENV

    - name: Build and push Docker images
      run: |
        for FOLDER in $FOLDERS; do
          # VERSIONED_IMAGE_NAME="${{ env.DOCKER_HUB_USERNAME }}/$FOLDER:${{ env.VERSION }}"
          LATEST_IMAGE_NAME="${{ env.DOCKER_HUB_USERNAME }}/$FOLDER:latest"
          
          docker build "$FOLDER" -t "$VERSIONED_IMAGE_NAME" -t "$LATEST_IMAGE_NAME"
          
          docker push "$VERSIONED_IMAGE_NAME"
          docker push "$LATEST_IMAGE_NAME"
        done