name: Build and Push Docker images

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch, adjust if necessary

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Determine the version
      id: get_version
      run: echo "VERSION=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
    
    - name: Read services from config
      id: read-services
      run: |
        SERVICES=$(cat support/services.conf | tr '\r\n' ' ')
        echo "SERVICES=$SERVICES" >> $GITHUB_ENV
        echo $SERVICES

    - name: Build and push Docker images
      run: |
        for SERVICE in $SERVICES; do
          echo "Building and pushing Docker image for $SERVICE"
          VERSIONED_IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/ase-social-network_$SERVICE:${{ env.VERSION }}"
          LATEST_IMAGE_NAME="${{ env.DOCKERHUB_USERNAME }}/ase-social-network_$SERVICE:latest"
          
          docker build "$SERVICE" -f "$SERVICE/Dockerfile.build" -t "$VERSIONED_IMAGE_NAME" -t "$LATEST_IMAGE_NAME"
          docker build "$SERVICE" -f "$SERVICE/Dockerfile.build" -t "$LATEST_IMAGE_NAME"
          
          docker push "$VERSIONED_IMAGE_NAME"
          docker push "$LATEST_IMAGE_NAME"
        done